steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$total-method-413610/vizdaleondc:$SHORT_SHA', '.']
  
  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$total-method-413610/vizdaleondc:$SHORT_SHA']
  
  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'ondc2vizdale'
      - '--image'
      - 'gcr.io/$total-method-413610/vizdaleondc:$SHORT_SHA'
      - '--region'
      - 'asia-south2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove this line if you want to restrict access
images:
  - 'gcr.io/$total-method-413610/vizdaleondc:$SHORT_SHA'
